// services/invoiceService.js
import { supabase } from "../config/supabaseClient.js";
import { generateInvoicePdfBuffer } from "./invoicePdf.js";
import { sendInvoiceEmail } from "./billingEmail.js";

/**
 * Enrolls a user in a course and issues an invoice automatically.
 * Safe to call from both payment verification and admin manual grant.
 *
 * @param {object} opts
 * @param {number} opts.userId
 * @param {number} opts.courseId
 * @param {number} opts.amount       - in rupees (not paise)
 * @param {'payment'|'manual'} opts.source
 * @param {string} [opts.notes]
 * @param {string} [opts.paymentId]  - razorpay internal payment row id, if from payment flow
 */
export const issueInvoiceAndEnroll = async ({
  userId,
  courseId,
  amount,
  source,
  notes,
  paymentId,
}) => {
  // 1. Fetch user and course (only needed fields)
  const { data: user, error: userError } = await supabase
    .from("users")
    .select("id, user_name, email")
    .eq("id", userId)
    .single();

  if (userError || !user) throw new Error("User not found");

  const { data: course, error: courseError } = await supabase
    .from("courses")
    .select("id, course_name, price, students_enrolled")
    .eq("id", courseId)
    .single();

  if (courseError || !course) throw new Error("Course not found");

  // 2. Enroll user atomically via RPC (avoids race condition)
  const { error: enrollError } = await supabase.rpc("append_student", {
    p_course_id: courseId,
    p_user_id: userId,
  });

  if (enrollError) throw new Error("Enrollment failed: " + enrollError.message);

  // 3. Insert invoice record FIRST (audit trail before email)
  const issueDate = new Date().toISOString().slice(0, 10);

  const { data: invoiceRow, error: invoiceError } = await supabase
    .from("invoices")
    .insert({
      user_id: userId,
      course_id: courseId,
      amount,
      notes: notes ?? null,
      source,              // 'payment' | 'manual'
      payment_id: paymentId ?? null,
      issue_date: issueDate,
    })
    .select("id, invoice_number")  // invoice_number is generated by Postgres (see step 5)
    .single();

  if (invoiceError) throw new Error("Invoice record failed: " + invoiceError.message);

  // 4. Generate PDF and send email
  const invoiceData = {
    invoiceNumber: invoiceRow.invoice_number,
    issueDate,
    user: {
      name: user.user_name || "Valued Customer",  // never fall back to email in salutation
      email: user.email,
    },
    course: {
      name: course.course_name,
      listedPrice: course.price,
    },
    amount,
    notes,
    source,
  };

  const pdfBuffer = await generateInvoicePdfBuffer(invoiceData);

  await sendInvoiceEmail({
    toEmail: user.email,
    toName: invoiceData.user.name,
    pdfBuffer,
    invoiceNumber: invoiceRow.invoice_number,
    courseName: course.course_name,
    amount,
  });

  return {
    invoiceId: invoiceRow.id,
    invoiceNumber: invoiceRow.invoice_number,
    enrolledCourseId: courseId,
    userId,
  };
};